### ISSUE TITLE
Diffing fonts with different family names doesn't display correctly

### ISSUE THREAD

**Issue by m4rc1e** [m4rc1e/diffenator2#10]

**Comment by simoncozens** [comment]
Came here to report same issue. This is because in the Javascript we just switch "old-XXX" for "new-XXX", using the old name both times, instead of using the new name. Perhaps a better way would be to have the CSS classes which set up the font families just be called "old-font" and "new-font".

**Comment by m4rc1e** [comment]
Will be fixed in https://github.com/m4rc1e/diffenator2/pull/11/commits/8c8bde36d46fe3736ec7321bb24e266413fdb92a
